# baseURL = 'https://ssk0206.github.io/blog/'
# languageCode = 'en-us'
DefaultContentLanguage = "ja"
title = 'えいりはすのブログ'
# custom_css = ["css/custom-font.css"]
theme = "hugo-theme-stack"

# [[module.imports]]
# path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[author]
    name = "Azu Arihas"
    bio = "新人エンジニア"
    job = "backend engineer"

mainSections = ["post"]
